[package]
name = "wasm-eu4"
version = "0.1.0"
authors = ["Nick Babcock <nbabcock19@hotmail.com>"]
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["miniz"]
miniz = ["eu4save/miniz", "eu4game/miniz"]
libdeflate = ["eu4save/libdeflate", "eu4game/libdeflate"]

[dependencies]
jomini = { version = "0.21" }
js-sys = "0.3"
once_cell = "1.13"
wasm-bindgen = { version = "0.2" }
serde-wasm-bindgen = "0.4"
serde = { version = "1", features = ["derive"] }
eu4save = { git = "https://github.com/rakaly/eu4save.git", default-features = false }
eu4game = { path = "../eu4game", default-features = false }
schemas = { path = "../schemas" }
tarsave = { path = "../tarsave" }
wasm-compress = { path = "../wasm-compress" }
asar-save = { path = "../asar-save" }
tar = "0.4"
zip = { version = "0.6", default-features = false, features = ["deflate"] }

[dev-dependencies]
wasm-bindgen-test = "0.3.0"

[package.metadata.wasm-pack.profile.release]
wasm-opt = false
