[package]
name = "pdx"
version = "0.1.0"
edition = "2021"
publish = false

[features]
admin = ["create_bundle", "fetch_assets", "tokenize", "dep:applib", "dep:eu4game", "dep:eu4save", "dep:flate2"]
fun = ["dep:applib", "dep:eu4game", "dep:eu4save", "dep:flate2"]

create_bundle = ["dep:zstd"]
compile_assets = ["dep:attohttpc", "dep:brotli", "dep:eu4save", "dep:jomini", "dep:oxipng", "dep:schemas", "schemas?/inline", "dep:zstd"]
fetch_assets = ["dep:aws-config", "dep:aws-sdk-s3", "dep:tokio", "dep:tokio-stream"]
tokenize = ["dep:brotli", "dep:schemas"]

[dependencies]
anyhow = "1.0"
applib = { path = "../applib", optional = true }
attohttpc = { version = "0.24", features = ["json"], optional = true }
aws-config = { version = "0.53.0", optional = true }
aws-sdk-s3 = { version = "0.23.0", optional = true }
brotli = { version = "3.3", optional = true }
chrono = "0.4"
clap = { version = "4.1", features = ["derive", "env"] }
csv = { version = "1.1" }
env_logger = "0.9"
eu4game = { path = "../eu4game", optional = true, default-features = false, features = ["libdeflate"] }
eu4save = { git = "https://github.com/rakaly/eu4save.git", default-features = false, features = ["serialize", "libdeflate"], optional = true }
filetime = "0.2"
flate2 = { version = "1.0", optional = true }
jomini = { version = "0.21", optional = true }
log = "0.4"
oxipng = { version = "8.0", optional = true, default-features = false, features = ["filetime", "parallel"] }
regex = "1"
schemas = { path = "../schemas", optional = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tar = "0.4"
tempfile = "3.3"
tokio = { version = "1", features = ["full"], optional = true }
tokio-stream = { version = "0.1.8", optional = true }
walkdir = "2.3.1"
zstd = { version = "0.12", features = ["zstdmt"], optional = true }
