[package]
name = "wasm-compress"
version = "0.1.0"
authors = ["Nick Babcock <nbabcock19@hotmail.com>"]
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = { version = "0.2" }
zip_next = { version = "0.11.0", default-features = false, features = ["deflate", "zstd"] }
zstd = { version = "0.13.0", default-features = false }
js-sys = "0.3"
tsify = { version = "0.4.5", default-features = false, features = ["js"] } 
serde = { version = "1.0", features = ["derive"] }

[package.metadata.wasm-pack.profile.release]
wasm-opt = false
