[package]
name = "wasm-compress"
version = "0.1.0"
authors = ["Nick Babcock <nbabcock19@hotmail.com>"]
edition = "2021"
publish = false

[dependencies]
wasm-bindgen = { version = "0.2" }
zip = { version = "0.6", default-features = false, features = ["deflate"] }
js-sys = "0.3"
flate2 = "1.0"
